//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultoriaSAS.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnvironmentSystem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnvironmentSystem() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsultoriaSAS.Web.Resources.EnvironmentSystem", typeof(EnvironmentSystem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adviser.
        /// </summary>
        internal static string Adviser {
            get {
                return ResourceManager.GetString("Adviser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes agregar un Rol.
        /// </summary>
        internal static string AggRol {
            get {
                return ResourceManager.GetString("AggRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código no válido..
        /// </summary>
        internal static string CodigoNoValido {
            get {
                return ResourceManager.GetString("CodigoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConfirmEmail.
        /// </summary>
        internal static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña o Correo Invalido.
        /// </summary>
        internal static string ContraseñaErrada {
            get {
                return ResourceManager.GetString("ContraseñaErrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CustomerId.
        /// </summary>
        internal static string CustomerId {
            get {
                return ResourceManager.GetString("CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DocumentTypeId.
        /// </summary>
        internal static string DocumentTypeId {
            get {
                return ResourceManager.GetString("DocumentTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ExternalLoginCallback.
        /// </summary>
        internal static string ExternalLoginCallback {
            get {
                return ResourceManager.GetString("ExternalLoginCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ExternalLoginConfirmation.
        /// </summary>
        internal static string ExternalLoginConfirmation {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ExternalLoginFailure.
        /// </summary>
        internal static string ExternalLoginFailure {
            get {
                return ResourceManager.GetString("ExternalLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ForgotPasswordConfirmation.
        /// </summary>
        internal static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Index.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intento de inicio de sesión no válido..
        /// </summary>
        internal static string IntentoNoValido {
            get {
                return ResourceManager.GetString("IntentoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lockout.
        /// </summary>
        internal static string Lockout {
            get {
                return ResourceManager.GetString("Lockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage.
        /// </summary>
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PqrTypeId.
        /// </summary>
        internal static string PqrTypeId {
            get {
                return ResourceManager.GetString("PqrTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ResetPasswordConfirmation.
        /// </summary>
        internal static string ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        internal static string RoleCreate {
            get {
                return ResourceManager.GetString("RoleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string RoleDelete {
            get {
                return ResourceManager.GetString("RoleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string RoleEdit {
            get {
                return ResourceManager.GetString("RoleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RoleID.
        /// </summary>
        internal static string RoleID {
            get {
                return ResourceManager.GetString("RoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View.
        /// </summary>
        internal static string RoleView {
            get {
                return ResourceManager.GetString("RoleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a luguerrero10@poligran.edu.co.
        /// </summary>
        internal static string SecretUser {
            get {
                return ResourceManager.GetString("SecretUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Luguerrero10*.
        /// </summary>
        internal static string SecretValue {
            get {
                return ResourceManager.GetString("SecretValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Seleccione un Rol...].
        /// </summary>
        internal static string SeleccionarRol {
            get {
                return ResourceManager.GetString("SeleccionarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SendCode.
        /// </summary>
        internal static string SendCode {
            get {
                return ResourceManager.GetString("SendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya se encuentra registrado en la base de datos.
        /// </summary>
        internal static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VerifyCode.
        /// </summary>
        internal static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WorkStationId.
        /// </summary>
        internal static string WorkStationId {
            get {
                return ResourceManager.GetString("WorkStationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XsrfId.
        /// </summary>
        internal static string XsrfId {
            get {
                return ResourceManager.GetString("XsrfId", resourceCulture);
            }
        }
    }
}
